FROM biocorecrg/debian-perlbrew-pyenv3-java:bullseye as jarserver

RUN apt update && apt upgrade -y
RUN mkdir -p /tmp
WORKDIR /tmp
COPY mvn* /tmp/
COPY pom.xml /tmp/
COPY src/ /tmp/src/
RUN mvn package -DskipTests -f pom.xml
# Result in target/*jar
RUN apt clean

FROM biocorecrg/debian-perlbrew-pyenv3-java:bullseye
VOLUME /tmp
RUN mkdir -p /config
RUN mkdir -p /app
RUN mkdir -p /secrets
WORKDIR /app
COPY --from=jarserver /tmp/target/*jar /app
COPY ./entrypoint.sh /app/
RUN chmod +x /app/entrypoint.sh
# We don't keep version number for making things easier
RUN mv /app/qsample-*.jar /app/qsample.jar
ENTRYPOINT /app/entrypoint.sh

