# spring.jpa.show-sql=true

server:
    port: 8081

application:
    version: dev

email-conf:
  address: roger.olivella@crg.eu
  admin-email: roger.olivella@crg.eu
  app-url: "http://localhost:4200"

spring:
    jackson:
        time-zone: UTC
    serialization:
        INDENT_OUTPUT: true
    datasource:
        ## MYSQL
        url: jdbc:mysql://database:3306/qsample?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
        username: "qsample"
        password: "qsample2017"
        driver-class-name: com.mysql.cj.jdbc.Driver
    mail:
      default-encoding: UTF-8
      host: smtp.crg.eu
      username: proteomics
      password: ****
      port: 587
      properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true
        protocol: smtp
        test-connection: false
    h2:
        console:
            enabled: false
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: MySQL57InnoDB
            format_sql: true
        show-sql: false
    flyway:
      locations:
        - classpath:/db/migration
      enabled: false

jwt:
    header: Authorization
    secret: L+0P1i+38a26pHiW10iHqPBYAyklvqPdySy98BV9PPCZyDogMggoSZkYxULqCF+WG6Nimlfxd53H6zjdIUJNJA==
    expiration: 604800
    route:
    authentication:
        path: api/auth
        refresh: refresh

qcloud2:
    disable: true
    url: https://api.qcloud2.crg.eu/qsample
    username: qsample
    password: qsample

neon-stats:
    disable: true
    url: http://neon.crg.eu/

nextflow-tower:
    disable: true
    token: xxx
    url: https://api.tower.nf/

agendo:
    username: qsample
    password: xxx
    from: Y3Jn
    url: https://api.qcloud2.crg.eu/mirror?url=https://api.agendoscience.com
    facility: 10

local-requests: true # true to use local database, false to use agendo. If true unlocks the request creation, delete and update form TODO

---

spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://database:3306/qsample?useSSL=false&serverTimezone=UTC
    username: "qsample"
    password: "qsample2017"
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: MySQL57InnoDB
    show-sql: false
  flyway:
    locations:
      - classpath:/db/migration
    enabled: false
server:
  port: 8099
email-conf:
  address: qcloud@crg.eu
  admin-email: roger.olivella@crg.eu
  #app-url: "http://qsample.crg.eu"
  app-url: "http://localhost:4200" 
logging:
  file: /tmp/qsample.log
  level:
    org.springframework:
    security: ERROR


spring.main.allow-bean-definition-overriding: true
