# spring.jpa.show-sql=true

server:
    port: 8081

application:
    version: dev

spring:
    jackson:
        time-zone: Europe/Madrid
    serialization:
        INDENT_OUTPUT: true
    datasource:
        ## MYSQL
        url: jdbc:mysql://127.0.0.1:3306/qsample?useSSL=false&serverTimezone=UTC
        username: "root"
        password: "vesperon501"
        driver-class-name: com.mysql.cj.jdbc.Driver

    h2:
        console:
            enabled: false
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: MySQL57InnoDB
            format_sql: true
        show-sql: false
    flyway:
        enabled: false

jwt:
    header: Authorization
    secret: L+0P1i+38a26pHiW10iHqPBYAyklvqPdySy98BV9PPCZyDogMggoSZkYxULqCF+WG6Nimlfxd53H6zjdIUJNJA==
    expiration: 604800
    route:
    authentication:
        path: api/auth
        refresh: refresh

qcloud2:
    url: https://api.qcloud2.crg.eu/qsample
    # url: http://localhost:5001/qsample
    username: qsample
    password: qsample

agendo:
    # username: marc.serret@crg.eu
    # password: cacaDeVaca1
    username: qsample
    password: qsample
    from: Y3Jn
    # url: https://api.agendo.science
    url: https://api.qcloud2.crg.eu/mirror?url=https://api.agendo.science
    facility: 10

---

spring:
  profiles: test
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/qsampletest?useSSL=false&serverTimezone=UTC
    username: "admin"
    password: "CRG4dm1n!"
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: MySQL57InnoDB
    show-sql: false
  flyway:
    enabled: false
server:
  port: 8081
logging:
  file: qsample.log
  level:
    org.springframework:
    security: ERROR