# spring.jpa.show-sql=true

server:
    port: 8081

application:
    version: dev

email-conf:
  address: qcloud@crg.eu
  admin-email: marc.serret@crg.eu
  app-url: "http://localhost:4200"

spring:
    jackson:
        time-zone: Europe/Madrid
    serialization:
        INDENT_OUTPUT: true
    datasource:
        ## MYSQL
        url: jdbc:mysql://127.0.0.1:3306/qsample?useSSL=false&serverTimezone=UTC
        username: "root"
        password: "***REMOVED***"
        driver-class-name: com.mysql.cj.jdbc.Driver
    mail:
      default-encoding: UTF-8
      host: smtp.crg.eu
      username: proteomics
      password: ***REMOVED***
      port: 587
      properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true
        protocol: smtp
        test-connection: false
    h2:
        console:
            enabled: false
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: MySQL57InnoDB
            format_sql: true
        show-sql: false
    flyway:
      locations:
        - classpath:/db/migration
      enabled: false

jwt:
    header: Authorization
    secret: L+0P1i+38a26pHiW10iHqPBYAyklvqPdySy98BV9PPCZyDogMggoSZkYxULqCF+WG6Nimlfxd53H6zjdIUJNJA==
    expiration: 604800
    route:
    authentication:
        path: api/auth
        refresh: refresh

qcloud2:
    disable: true
    url: https://api.qcloud2.crg.eu/qsample
    # url: http://localhost:5001/qsample
    username: qsample
    password: qsample

neon-stats:
    disable: true
    url: http://neon.crg.eu/

nextflow-tower:
    disable: true
    token: eyJ0aWQiOiAzOTM3fS42Mjc0MjQ0YzI3NjBmZmU3ZmQxNTc4Y2M1OGE0YzM5NjA0MjkxZWI3
    url: https://api.tower.nf/

agendo:
    # username: marc.serret@crg.eu
    # password: cacaDeVaca1
    username: qsample
    password: qsample
    from: Y3Jn
    url: https://api.qcloud2.crg.eu/mirror?url=https://api.agendoscience.com
    facility: 10

---

spring:
  profiles: test
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/qsampletest?useSSL=false&serverTimezone=UTC
    username: "admin"
    password: "CRG4dm1n!"
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: MySQL57InnoDB
    show-sql: false
  flyway:
    locations:
      - classpath:/db/migration
    enabled: false
server:
  port: 8081
email-conf:
  address: qcloud@crg.eu
  admin-email: marc.serret@crg.eu
  app-url: "qsample.crg.eu"
logging:
  file: qsample.log
  level:
    org.springframework:
    security: ERROR

---
spring:
  profiles: unittest
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/qsampleunit?useSSL=false&serverTimezone=UTC
    username: "root"
    password: "***REMOVED***"
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: MySQL57InnoDB
    show-sql: false

  flyway:
    locations:
      - classpath:/db/test-migration
    enabled: true
server:
  port: 8082
logging:
  file: qsampleUnitTest.log

spring.main.allow-bean-definition-overriding: true